<?= $header ?>
<main>
<section class="container">
    <div class="condiciones">
        <h1>Políticas de Privacidad</h1>
        <p>La información suministrada por el Usuario en el Sitio conformará una base de datos (en adelante, "Base de Datos") que será utilizada únicamente para la finalidad descripta, de acuerdo a los lineamientos de la Ley 25.326 de Protección de Datos Personales. La misma se encuentra inscripta bajo las formas y modalidades que impone la ley de rito. La información consignada de ninguna manera será cedida a terceras personas ajenas al Sitio. El Usuario, podrá en cualquier momento ejercer los derechos de acceso, rectificación y supresión de los datos consignados en la Base de Datos y asimismo es su deber comunicar cualquier cambio de los mismos al Sitio, a fin de mantener los mismos exactos y actualizados. Conforme artículo 14, inciso 3 de la Ley Nº 25.326, el titular de los datos personales posee la facultad de ejercer el derecho de acceso a los mismos en forma gratuita en intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de la información personal facilitada, y se comprometen a mantenerla actualizada. Una vez registrado en el Sitio, el Usuario podrá revisar y cambiar la información que proporcionó durante el proceso de registración incluyendo:</p>
        <ul>
            <li>El seudónimo y dirección de correo electrónico. Sin perjuicio de los cambios que realice, <span>KEEPGREEN SA</span>, conservará la información personal anterior por motivos de seguridad y control del fraude.</li>
            <li>La información de la registración como: compañía, domicilio, ciudad, región, código postal, país, número principal de teléfono, número secundario de teléfono, número de fax, correo electrónico, etc.</li>
            <li>La clave personal</li>
        </ul>
        <p>Con las excepciones que establece el Art. 17 de la Ley 25.326.</p>
        <p><span>KEEPGREEN SA</span>, podrá modificar en cualquier momento los términos y condiciones de su Política de Privacidad y/o las prácticas de envío de e-mails. Si se decide introducir algún cambio material a la Política de Privacidad, se notificará publicando una versión actualizada de las Política en esta sección o mediante el envío de un e-mail o informándolo en la página principal u otras secciones del Sitio para mantener al Usuario actualizado de los cambios realizados. De igual manera si <span>KEEPGREEN SA</span>, decide realizar cambios materiales en la forma en que se administra la información personal del Usuario, se notificará por e-mail para que éste pueda tomar una decisión informada respecto sobre aceptar o no que dicha información personal sea utilizada de tal forma.</p>
        <p><span>KEEPGREEN SA</span>, emplea técnicas necesarias de seguridad para proteger tales datos de accesos no autorizados por Usuarios dentro o fuera de nuestra compañía. Sin embargo, en función de los avances tecnológicos, y la inseguridad virtual existente <span>KEEPGREEN SA</span> no se hace responsable por interceptaciones ilegales o violaciones de sus sistemas o bases de datos por parte de personas no autorizadas, como así tampoco por la indebida utilización de la información obtenida por esos medios.</p>
        <p><span>KEEPGREEN SA</span> mantendrá la confidencialidad de la información recibida por el usuario, en tanto tal información no haya tomado estado público o haya sido requerida a <span>KEEPGREEN SA</span> por autoridad competente para ello. En su caso <span>KEEPGREEN SA</span> podrá revelar la información personal de sus Usuarios bajo requerimiento de las autoridades judiciales o gubernamentales competentes para efectos de investigaciones conducidas por ellas, <span>KEEPGREEN SA</span> puede (y los Usuarios lo autorizan expresamente) comunicar cualquier información personal sobre sus usuarios con la finalidad de cumplir la normativa aplicable y cooperar con las autoridades competentes en la medida en que discrecionalmente se considere necesario y adecuado en relación con cualquier investigación de un ilícito o un fraude, infracción de derechos de propiedad industrial o intelectual, u otra actividad que sea ilegal o que pueda exponer a <span>KEEPGREEN SA</span> o a sus Usuarios a cualquier responsabilidad legal.
        </p>
        <p>Los Usuarios aceptan que <span>KEEPGREEN SA</span> tiene derecho a comunicarse con ellos por vía postal, telefónica o electrónica y enviar información que la empresa considere a su exclusivo criterio que pueda ser de su interés, incluyendo publicidad e información sobre ofertas y promociones. En caso de que los Usuarios no deseen ser contactados con estos fines, podrán manifestar su voluntad fehacientemente a <span>KEEPGREEN SA</span> quien procederá a interrumpir este tipo de comunicaciones en el menor tiempo que le sea posible.</p>
        <h4>Normas y procedimientos de confidencialidad:</h4>
        <p><span>KEEPGREEN SA</span> no vende, cede o lucra de otra manera con su información personal. Los usuarios autorizan al registro por cualquier medio la información que ingresen en el Sitio otorgando a dichas registraciones valor probatorio. Todos los accesos a la base de datos, tanto desde el Sitio como desde nuestras oficinas están regulados por mecanismos de seguridad informática que garantizan su integridad y privacidad.</p>
        <h4>Cookies</h4>
        <p>El Usuario del Sitio conoce y acepta que <span>KEEPGREEN SA</span> podrá utilizar un sistema de seguimiento mediante la utilización de cookies (las "Cookies"). Las Cookies son pequeños archivos que se instalan en el disco rígido, con una duración limitada en el tiempo que ayudan a personalizar los servicios. Las Cookies se utilizan con el fin de conocer los intereses, el comportamiento y la demografía de quienes visitan o son Usuarios de nuestro Sitio y de esa forma, comprender mejor sus necesidades e intereses y darles un mejor servicio o proveer información relacionada. También se utiliza la información obtenida por intermedio de las Cookies para analizar las páginas navegadas por el Usuario, las búsquedas realizadas, mejorar nuestras iniciativas comerciales y promocionales, mostrar publicidad o promociones, banners de interés, noticias sobre <span>KEEPGREEN SA</span>, perfeccionar nuestra oferta de contenidos y artículos, personalizar dichos contenidos, presentación y servicios.
        <span>KEEPGREEN SA</span> podrá agregar Cookies en los e-mails que envíe para medir la efectividad de las promociones.</p>
        <p>Se utilizan adicionalmente las Cookies para que el Usuario no tenga que introducir su clave frecuentemente durante una sesión de navegación, también para contabilizar y corroborar las registraciones, siempre teniendo como objetivo de la instalación de las Cookies, el beneficio del Usuario que la recibe, y no será usado con otros fines ajenos.</p>
        <p>Se aclara expresamente que estas políticas cubren la utilización de Cookies por este sitio y no la utilización de Cookies por parte de anunciantes. <span>KEEPGREEN SA</span> no controla el uso de Cookies por terceros.</p>
    </div>
</section>
</main>
<?= $footer ?>