<?= $header ?>
<main>
<section class="container">
    <div class="condiciones">
        <h1>Términos y condiciones</h1>
        <p>Bienvenido, usted ha accedido al sistema de ventas on line de <span>Keepgreen SA</span>. Las Condiciones de Uso, que se describen a continuación tienen por objeto regular el uso que realicen las personas que ingresen al Sitio. Por "Usuario" de la web se entiende tanto a los registrados como a los visitantes, (en adelante el "Usuario"). Su utilización implica la adhesión sin reservas a las condiciones de uso estipuladas en el presente reglamento.
        Al ingresar en el Sitio, el Usuario declara saber, conocer y aceptar las presentes Condiciones de Uso.
        Las Condiciones de Uso, así como sus modificaciones, estarán vigentes en forma inmediata a su publicaciónen el Sitio bastando esta publicación como notificación de la misma. La utilización del Sitio implica elconocimiento y la aceptación plena por parte del Usuario de las Condiciones de Uso.
        Cualquier persona que no acepte estos términos y condiciones generales, los cuales tienen un carácterobligatorio y vinculante, deberá abstenerse de utilizar el sitio y/o los servicios.</p>
        <h3>CAPACIDAD</h3>
        <p>Podrán operar en “el sitio” personas que sean capaces para contratar conforme lo establecido por el Código Civil y Comercial, y leyes aplicables (en adelante el usuario). No podrán hacer uso del sitio aquellas personas que no posean dicha capacidad legal, quienes hayan sido suspendidos o inhabilitados, ni los menores de edad.</p>
        <h3>PROPIEDAD INTELECTUAL</h3>
        <p><span>KEEPGREEN SA</span> el sitio web, sus logotipos y todo el material que aparece en dicho sitio, son marcas, nombres de dominio, avisos comerciales y nombres comerciales propiedad de sus respectivos titulares y están protegidos por los tratados internacionales y las leyes aplicables en materia de propiedad intelectual, Ley 11.723. Los derechos de autor sobre el contenido, organización, recopilación, compilación, información, logotipos, fotografías, imágenes, programas, aplicaciones, y en general cualquier información contenida o publicada en el sitio web se encuentran debidamente protegidos a favor de sus respectivos propietarios y correctamente licenciados, de conformidad con la legislación aplicable en materia de propiedad intelectual e industrial. Se prohíbe expresamente al usuario modificar, alterar o suprimir, ya sea en forma total o parcial, los avisos, marcas, nombres comerciales, señas, anuncios, logotipos o en general cualquier indicación que se refiera a la propiedad de la información contenida en el sitio.</p>
        <h3>PROHIBICIONES AL USUARIO Y SUS RESPONSABILIDADES</h3>
        <p>Está terminantemente prohibido al Usuario explotar de cualquier forma las informaciones adquiridas por medio del Sitio. No podrá reproducir los textos o imágenes para otros fines que los exclusivos del objeto de compra. Será responsabilidad del Usuario cualquier acto que se derive del uso del sitio y que implique un daño a <span>KEEPGREEN SA</span> o a terceros y acepta mantener indemne a estos, respecto de y contra cualquier reclamo por parte de terceros, derivado o relacionado con el uso inadecuado del Sitio o por la violación de las presentes Condiciones de Uso y sus respectivas modificaciones, o que surja de dicho uso y/o a causa de algún comentario publicado por el Usuario en el Sitio. En tal sentido, está prohibido a los Usuarios violar, vulnerar y/o de cualquier forma afectar el normal uso y la seguridad del Sitio.</p>
        <h3>MODIFICACIONES DE LOS TÉRMINOS Y CONDICIONES</h3>
        <p>El Sitio se reserva expresamente los siguientes derechos: (i) A modificar o eliminar, en forma unilateral, parcial o totalmente, tanto la disposiciones de los elementos que componen el Sitio, como su configuración general o particular, los servicios o contenidos o sus condiciones de acceso y utilización; (ii) A denegar o retirar el acceso a este Sitio, sus servicios y contenidos, en cualquier momento y sin aviso previo, a aquellos visitantes que incumplan los Términos y Condiciones, (iii) A poner término, suspender o interrumpir unilateralmente, en cualquier momento y sin aviso previo, la prestación del servicio del Sitio, (iv) A modificar los términos de los Términos y Condiciones en cualquier momento.</p>
        <h3>TERMINACIÓN</h3>
        <p><span>KEEPGREEN SA</span> se reserva el derecho, a su exclusiva discreción, y sin necesidad de aviso o notificación al usuario, para a) Terminar definitivamente el presente contrato y b) Descontinuar o dejar de publicar definitivamente el sitio web sin responsabilidad alguna para KEEPGREEN SA, sus afiliados o proveedores.</p>
        <h3>LEY APLICABLE, JURISDICCIÓN Y COMPETENCIA</h3>
        <p>Los Términos y Condiciones serán interpretados y ejecutados de acuerdo a las leyes de la República de Argentina. El Usuario se somete incondicionalmente a la jurisdicción de los Tribunales de la Ciudad de Corrientes para la resolución de cualquier duda, dificultad o controversia relacionada con todo o parte de los Términos y Condiciones. Domicilios y notificaciones Todas las notificaciones vinculadas con los presentes Términos y Condiciones se considerarán notificadas a los usuarios con la mera publicación de las mismas en el sitio. Las notificaciones que los usuarios pretendan cursar al sitio deberán ser remitidas a Santiado del Estero 668 Corrientes Argentina, el cual será considerado su domicilio constituido.</p>
    </div>
</section>
</main>
<?= $footer ?>